export { default as loginSchema } from './login'
export { default as registerSchema } from './register'
export { default as resetPasswordSchema } from './resetPassword'
export { default as editProfileSchema } from './editProfile'
export { default as basePasswordSchema } from './basePassword'
export { default as forgetPasswordSchema } from './forgetPassword'
export { default as editPasswordSchema } from './password'